##### *데이터 형식

고대석_걷기_보통_2.xlsx
고대석_걷기_무게중심_후방_5.xlsx
고대석_걷기_무게중심_전방_5.xlsx
고대석_걷기_무게중심_우측_5.xlsx
고대석_걷기_무게중심_좌측_5.xlsx
이우람_걷기_무게중심_우_5.xlsx
이우람_걷기_무게중심_좌_5.xlsx
이우람_걷기_무게중심_전_5.xlsx
이우람_걷기_무게중심_후_5.xlsx

In [2]:
from glob import glob
from os.path import isdir
import os
import pandas as pd

In [3]:
# train
datapath="../data/*/*"

walkingtype=["걷기_보통_","무게중심_좌","무게중심_우","무게중심_전","무게중심_후"]

dic={}
for ty in walkingtype:
    dic[ty]=pd.DataFrame
#walkingdf=[walkdf,leftdf,rightdf,frontdf,backdf]
#dic=dict(zip(walkingtype,walkingdf))

print(dic.keys())
label=0
for k,v in dic.items():
    for idx in range(1,5):
        for x in glob(datapath+k+"*"+str(idx)+"*"):
            tempdf=pd.read_excel(open(x,'rb'))
            tempdf=tempdf[['x','y','z']]
            tempdf['label']=label
            if len(tempdf)!=234:
                print(x,len(tempdf))
            v=pd.concat([tempdf,v])
            dic[k]=v
    label+=1

dict_keys(['무게중심_우', '무게중심_전', '무게중심_후', '무게중심_좌', '걷기_보통_'])
../data/송재현/송재현_걷기_무게중심_우_2.xlsx 235
../data/장승원/장승원_걷기_무게중심_좌_1.xlsx 235
../data/이종모/이종모_걷기_보통_2.xlsx 235

In [4]:
label=4 
for dickey,k,v in zip(["무게중심_전","무게중심_후"],['무게중심_앞','무게중심_뒤'],[frontdf,backdf]): 
    for idx in range(1,5):
            for x in glob(datapath+k+"*"+str(idx)+"*"):
                tempdf=pd.read_excel(open(x,'rb'))
                tempdf=tempdf[['x','y','z']]
                tempdf['label']=label
                if len(tempdf)!=234:
                    print(x,len(tempdf))
                dic[dickey]=pd.concat([dic[dickey],tempdf])
                
    label-=2

../data/이종모/이종모_걷기_무게중심_앞_1.xlsx 236
../data/심준석/심준석_걷기_무게중심_뒤_3.xlsx 235

In [5]:
for k,v in dic.items():
    print(k,len(v))
    print(v.head())

무게중심_우 9361
        x        y       z  label
0  -333.0   9664.0  2624.0      0
1 -2701.0  14208.0  5184.0      0
2 -1677.0  14400.0  3392.0      0
3    50.0  17792.0  2368.0      0
4 -2189.0  13696.0  1152.0      0
무게중심_전 9362
        x        y       z  label
0  -383.0  16128.0  1280.0      1
1    64.0  17472.0  1216.0      1
2    64.0  18432.0  1472.0      1
3 -1535.0  19136.0  2624.0      1
4 -1535.0  20224.0  1664.0      1
무게중심_후 9361
        x        y       z  label
0 -3289.0  14080.0  3072.0      2
1 -2585.0  15040.0  2752.0      2
2   678.0  15808.0  1152.0      2
3  1830.0  16128.0  1536.0      2
4   806.0  17472.0  1152.0      2
무게중심_좌 9361
        x        y       z  label
0  -216.0  14400.0  1280.0      3
1 -1048.0  17664.0  1600.0      3
2 -1752.0  18752.0  2496.0      3
3  1063.0  20736.0  2048.0      3
4  1511.0  23168.0  1088.0      3
걷기_보통_ 9361
        x        y       z  label
0 -1659.0  21952.0  5440.0      4
1  -315.0  17088.0  8000.0      4
2  6596.0   9856.0  2560.0      4
3  1988.0  16384.0  6144.0      4
4  -955.0  18496.0  3072.0      4

In [6]:
testdict={}
for ty in walkingtype:
    testdict[ty]=pd.DataFrame

for k,v in dic.items():
    for x in glob(datapath+k+"*"+str(5)+"*"):
        tempdf=pd.read_excel(open(x,'rb'))
        tempdf=tempdf[['x','y','z']]
        tempdf['label']=label
        if len(tempdf)!=234:
            print(x,len(tempdf))
        v=pd.concat([tempdf,v])
        testdict[k]=v
    label+=1
label=4   
for dickey,k,v in zip(["무게중심_전","무게중심_후"],['무게중심_앞','무게중심_뒤'],[frontdf,backdf]): 
    
    for x in glob(datapath+k+"*"+str(5)+"*"):
        tempdf=pd.read_excel(open(x,'rb'))
        tempdf=tempdf[['x','y','z']]
        tempdf['label']=label
        if len(tempdf)!=234:
            print(x,len(tempdf))
        testdict[dickey]=pd.concat([testdict[dickey],tempdf])
                
    label-=2

In [7]:
for k,v in testdict.items():
    print(k,len(v))
    print(v.head())

무게중심_우 11701
        x        y        z  label
0  2418.0  15168.0  10368.0      0
1 -6925.0  11008.0   9344.0      0
2  3058.0  17664.0   6720.0      0
3  2226.0  16064.0   4352.0      0
4 -1037.0  11392.0   3072.0      0
무게중심_전 11702
        x        y       z  label
0     0.0  16960.0 -1216.0      1
1   576.0  17856.0  -448.0      1
2 -1023.0  18496.0  2112.0      1
3 -2239.0  20736.0  -576.0      1
4 -3007.0  22400.0  5696.0      1
무게중심_후 11701
        x        y        z  label
0  2086.0  15936.0  10240.0      2
1 -4825.0  11264.0   9088.0      2
2   -89.0  14720.0   8256.0      2
3   358.0  15552.0   5504.0      2
4   806.0  11520.0   4608.0      2
무게중심_좌 11701
        x        y       z  label
0  7079.0  11200.0  5440.0      3
1 -3672.0  16384.0  7360.0      3
2   103.0  13760.0  6656.0      3
3  3559.0  10816.0  3008.0      3
4  1767.0  11392.0  3200.0      3
걷기_보통_ 11701
        x        y       z  label
0   516.0  16832.0  -448.0      4
1    68.0  17920.0  -960.0      4
2  -251.0  18048.0   512.0      4
3 -1083.0  18816.0  -384.0      4
4   452.0  22400.0  3712.0      4

In [10]:
traindf=pd.DataFrame()
testdf=pd.DataFrame()
for k,v in dic.items():
    traindf=pd.concat([traindf,v])
for k,v in testdict.items():
    testdf=pd.concat([testdf,v])
traindf.to_csv('../data/train_data.csv')
testdf.to_csv('../data/test_data.csv')

In [12]:
traindf=pd.read_csv("../data/train_data.csv")
testdf=pd.read_csv("../data/test_data.csv")

In [13]:
traindf

       Unnamed: 0        x        y        z  label
0               0   -333.0   9664.0   2624.0      0
1               1  -2701.0  14208.0   5184.0      0
2               2  -1677.0  14400.0   3392.0      0
3               3     50.0  17792.0   2368.0      0
4               4  -2189.0  13696.0   1152.0      0
5               5   -589.0  17152.0   2944.0      0
6               6   -397.0  19072.0   2112.0      0
7               7    114.0  18688.0   -448.0      0
8               8  -3981.0  18944.0  11712.0      0
9               9   1394.0  13184.0   8832.0      0
10             10  10162.0  10880.0   6720.0      0
11             11    114.0  15872.0   6976.0      0
12             12  -3917.0  15424.0   5184.0      0
13             13   3058.0  10880.0   4800.0      0
14             14   1906.0  12608.0   3776.0      0
15             15   -589.0  13888.0   3840.0      0
16             16     50.0  14912.0   1984.0      0
17             17    178.0  16320.0   2560.0      0
18             18    -77.0  18240.0   4096.0      0
19             19   1778.0  21312.0   2368.0      0
20             20   1906.0  22016.0   3584.0      0
21             21   2610.0  17728.0  12608.0      0
22             22  -1869.0  10880.0   9920.0      0
23             23  -1741.0  11264.0   7744.0      0
24             24   1202.0  14784.0   5760.0      0
25             25   2482.0  14400.0   5440.0      0
26             26   -525.0  11392.0   2880.0      0
27             27   -397.0  15360.0   3456.0      0
28             28  -1165.0  14272.0   3264.0      0
29             29   -397.0  15488.0    960.0      0
...           ...      ...      ...      ...    ...
46776         204    825.0  14912.0   4352.0      4
46777         205    313.0  15488.0   3520.0      4
46778         206    825.0  16256.0   3072.0      4
46779         207    953.0  18432.0   3072.0      4
46780         208   2041.0  18560.0   6528.0      4
46781         209   2425.0  22080.0  11648.0      4
46782         210  -3910.0  12480.0   8832.0      4
46783         211  -1094.0  14720.0   9856.0      4
46784         212   3385.0  16896.0   6336.0      4
46785         213   1273.0  12672.0   5056.0      4
46786         214  -1094.0   9088.0   2624.0      4
46787         215  -2886.0  11392.0   4928.0      4
46788         216  -1734.0  13376.0   5376.0      4
46789         217   -262.0  15552.0   3584.0      4
46790         218  -1158.0  16512.0   2560.0      4
46791         219   -966.0  19008.0   4544.0      4
46792         220     57.0  18816.0   3008.0      4
46793         221    121.0  20416.0   7360.0      4
46794         222  -1222.0  16704.0  11776.0      4
46795         223   2745.0  10048.0   9728.0      4
46796         224    633.0  13248.0   6912.0      4
46797         225  -1798.0  15744.0   7552.0      4
46798         226  -1094.0  11520.0   5184.0      4
46799         227    761.0   9984.0   4352.0      4
46800         228    185.0  12032.0   4480.0      4
46801         229   -134.0  14656.0   3840.0      4
46802         230   -326.0  14720.0   3200.0      4
46803         231   -774.0  17280.0   3584.0      4
46804         232      NaN      NaN      NaN      4
46805         233      NaN      NaN      NaN      4

[46806 rows x 5 columns]

In [14]:
testdf

       Unnamed: 0        x        y        z  label
0               0   2418.0  15168.0  10368.0      0
1               1  -6925.0  11008.0   9344.0      0
2               2   3058.0  17664.0   6720.0      0
3               3   2226.0  16064.0   4352.0      0
4               4  -1037.0  11392.0   3072.0      0
5               5   -525.0  11136.0   2752.0      0
6               6  -1165.0  12928.0   3584.0      0
7               7   -333.0  15232.0   1536.0      0
8               8     50.0  16640.0    704.0      0
9               9   -653.0  16384.0   1344.0      0
10             10   -397.0  19520.0   2624.0      0
11             11  -2957.0  19072.0    256.0      0
12             12  -3149.0  20672.0   4096.0      0
13             13  -1869.0  16768.0   8512.0      0
14             14  10098.0  10112.0   5440.0      0
15             15   -205.0  14720.0   5760.0      0
16             16  -5133.0  16768.0   5952.0      0
17             17   2930.0  11072.0   4096.0      0
18             18   2994.0  10496.0   3392.0      0
19             19   1522.0  12608.0   3584.0      0
20             20   1138.0  15744.0   2048.0      0
21             21    562.0  17152.0   2432.0      0
22             22   -845.0  17792.0   3456.0      0
23             23   5426.0  19968.0   3328.0      0
24             24   1266.0  20672.0     64.0      0
25             25    562.0  19392.0   5184.0      0
26             26   3826.0  16640.0  11968.0      0
27             27  -5965.0   9600.0   9408.0      0
28             28    498.0  13056.0   7424.0      0
29             29   2866.0  16640.0   5184.0      0
...           ...      ...      ...      ...    ...
58476         204    825.0  14912.0   4352.0      4
58477         205    313.0  15488.0   3520.0      4
58478         206    825.0  16256.0   3072.0      4
58479         207    953.0  18432.0   3072.0      4
58480         208   2041.0  18560.0   6528.0      4
58481         209   2425.0  22080.0  11648.0      4
58482         210  -3910.0  12480.0   8832.0      4
58483         211  -1094.0  14720.0   9856.0      4
58484         212   3385.0  16896.0   6336.0      4
58485         213   1273.0  12672.0   5056.0      4
58486         214  -1094.0   9088.0   2624.0      4
58487         215  -2886.0  11392.0   4928.0      4
58488         216  -1734.0  13376.0   5376.0      4
58489         217   -262.0  15552.0   3584.0      4
58490         218  -1158.0  16512.0   2560.0      4
58491         219   -966.0  19008.0   4544.0      4
58492         220     57.0  18816.0   3008.0      4
58493         221    121.0  20416.0   7360.0      4
58494         222  -1222.0  16704.0  11776.0      4
58495         223   2745.0  10048.0   9728.0      4
58496         224    633.0  13248.0   6912.0      4
58497         225  -1798.0  15744.0   7552.0      4
58498         226  -1094.0  11520.0   5184.0      4
58499         227    761.0   9984.0   4352.0      4
58500         228    185.0  12032.0   4480.0      4
58501         229   -134.0  14656.0   3840.0      4
58502         230   -326.0  14720.0   3200.0      4
58503         231   -774.0  17280.0   3584.0      4
58504         232      NaN      NaN      NaN      4
58505         233      NaN      NaN      NaN      4

[58506 rows x 5 columns]